#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Get the current OS name
case $(uname) in
  Darwin) os=mac ;;
  Linux) os=linux ;;
  *) exit 1 ;;
esac

# asdf
case $os in
  mac) . /usr/local/opt/asdf/libexec/asdf.sh ;;
  linux) . /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh ;;
esac

# Incremental history search with peco
# Refs: https://qiita.com/shepabashi/items/f2bc2be37a31df49bca5
function peco-history-selection() {
  case $os in
    mac) command="tail -r" ;;
    linux) command=tac ;;
  esac

  BUFFER=$(history -n 1 | "$command" | awk '!a[$0]++' | peco)
  CURSOR=$#BUFFER
  zle reset-prompt
}

zle -N peco-history-selection
bindkey '^R' peco-history-selection

# Suppress brew doctor warning caused by asdf python
# Refs: https://zenn.dev/ryuu/scraps/fddefc2ca60f88
case $os in
  mac) alias brew="PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin brew" ;;
esac

# OS specific settings

# Mac
if [ "$os" = "mac" ]; then
  export PATH=$HOME/bin:$PATH
  # export PATH="/usr/local/opt/openssl/bin:$PATH"
fi

# Linux
if [ "$os" = "linux" ]; then
  # Path settings

  # VS Code
  win_user_path=$(wslpath "$(wslvar USERPROFILE)")
  export PATH=$PATH:"$win_user_path/AppData/Local/Programs/Microsoft VS Code/bin"

  # GPG
  export GPG_TTY=$(tty)

  # SSH
  /usr/bin/keychain -q --nogui "$HOME"/.ssh/id_rsa
  source "$HOME"/.keychain/"$HOST"-sh
fi
