#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Get the current OS name
case $(uname) in
  Darwin) os=mac ;;
  Linux) os=linux ;;
  *) exit 1 ;;
esac

# Incremental history search with peco
# Refs: https://qiita.com/shepabashi/items/f2bc2be37a31df49bca5
function peco-history-selection() {
  case $os in
    mac) BUFFER=$(history -n 1 | tail -r | awk '!a[$0]++' | peco) ;;
    linux) BUFFER=$(history -n 1 | tac | awk '!a[$0]++' | peco) ;;
  esac

  CURSOR=$#BUFFER
  zle reset-prompt
}

zle -N peco-history-selection
bindkey '^R' peco-history-selection

# Suppress brew doctor warning caused by asdf python
# Refs: https://zenn.dev/ryuu/scraps/fddefc2ca60f88
# case $os in
  # Intel
  # mac) alias brew="PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin brew" ;;
# esac

# direnv
eval "$(direnv hook zsh)"

# For `$ rails app:update`
export THOR_MERGE="code -d $1 $2"

export PATH=${HOME}/bin:${PATH}

# OS specific settings

# Mac
if [ "$os" = "mac" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)" # Apple silicon
  # PostgreSQL
  export PATH="/opt/homebrew/opt/postgresql@15/bin:${PATH}"
  export LDFLAGS="-L/opt/homebrew/opt/postgresql@15/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/postgresql@15/include"
  # export PATH="/usr/local/opt/openssl/bin:$PATH"
fi

# Linux
if [ "$os" = "linux" ]; then
  # Path settings

  # VS Code
  win_user_path=$(wslpath "$(wslvar USERPROFILE)")
  export PATH=$PATH:"$win_user_path/AppData/Local/Programs/Microsoft VS Code/bin"

  # Homebrew
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

  # GPG
  export GPG_TTY=$(tty)

  # SSH
  /usr/bin/keychain -q --nogui "$HOME"/.ssh/id_ed25519
  source "$HOME"/.keychain/"$HOST"-sh
fi

# asdf
case $os in
  mac) . /opt/homebrew/opt/asdf/libexec/asdf.sh ;; # Apple silicon
  # mac) . /usr/local/opt/asdf/libexec/asdf.sh ;; # Intel
  linux) . /home/linuxbrew/.linuxbrew/opt/asdf/libexec/asdf.sh ;;
esac

# ESP-IDF

# ESP-IDF を使わないときはアンコメント。使うときはコメントアウト
asdf global python 3.11.5

# ESP-IDF を使わないときはコメントアウト。使うときはアンコメント
# asdf global python 3.9.6
# alias get_idf='. $HOME/esp/esp-idf/export.sh'
# export PATH=${HOME}/.espressif/python_env/idf4.4_py3.9_env/bin:${PATH}
